### ISSUE TITLE
Multiple configuration is being created on clicking save button in configuring new response

### ISSUE THREAD

**Issue by iamyusuf** [mock-wave/mockwave.io-disscussion#1]
<img width="1708" alt="Screenshot 2024-12-19 at 11 10 44 AM" src="https://github.com/user-attachments/assets/91d0fdc4-c9c8-4f68-ab01-faea03786aa7" />

Multiple configuration is being created on clicking save button in configuring new response

**Comment by hasanalihaolader** [comment]
When clicking the save button multiple times instead of one click, it will save the same response multiple times.

**Comment by hasanalihaolader** [comment]
@iamyusuf  Fixed and deployed in v1.0.1
